version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_URI=mongodb://mongodb:27017/test
      - JWT_SECRET=tercesrotarenegysae
      - JWT_EXPIRES=3d

  mongodb:
    image: mongo
    ports:
      - '27017:27017' 